### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by VIM-Arcange** [qqcky/GolosBoard#5]
We should create a landing page for people accessing the website via **http://golosboard.com** or **http://www.golosboard.com** without any parameter.

Actually, it shows an empty dashboard, which is not pretty.

The landing page should contains:
- a description of the site
- a search box to access a user's dashboard

**Comment by qqcky** [comment]
Done 👍

**Comment by VIM-Arcange** [comment]
Characters are not displayed when you type the username.
Tested on IE11 and Firefox 50.1

**Comment by qqcky** [comment]
Fixed 👍
